Imports Magna.DualTester.Core

Public Class StringDefaults
    Implements IStringDefaults

    Private ReadOnly _defaultPartAlarms As New Dictionary(Of Integer, String) From {{0, "Spare"},
                                                                                    {1, "Spare"},
                                                                                        {2, "Spare"},
                                                                                        {3, "Spare"},
                                                                                        {4, "Spare"},
                                                                                        {5, "Spare"},
                                                                                        {6, "Spare"},
                                                                                        {7, "Spare"},
                                                                                        {8, "Spare"},
                                                                                        {9, "Spare"},
                                                                                        {10, "Mirror Down Memory Resolution Fault - Measured Lower than Setpoint"},
                                                                                        {11, "Mirror Down Memory Resolution Fault - Measured Higher than Setpoint"},
                                                                                        {12, "Mirror Left Memory Resolution Fault - Measured Lower than Setpoint"},
                                                                                        {13, "Mirror Left Memory Resolution Fault - Measured Higher than Setpoint"},
                                                                                        {14, "Mirror Right Memory Resolution Fault - Measured Lower than Setpoint"},
                                                                                        {15, "Mirror Right Memory Resolution Fault - Measured Higher than Setpoint"},
                                                                                        {16, "Mirror Up Memory Resolution Fault - Measured Lower than Setpoint"},
                                                                                        {17, "Mirror Up Memory Resolution Fault - Measured Higher than Setpoint"},
                                                                                        {18, "Spare"},
                                                                                        {19, "Defog InRush Current Measurement Fault - InRush Measured Higher than Setpoint"},
                                                                                        {20, "BZI Current Measurement Fault - Measured Higher than Setpoint"},
                                                                                        {21, "BZI Current Measurement Fault - Measured Lower than Setpoint"},
                                                                                        {22, "Defog Current Measurement Fault - Measured Higher than Setpoint"},
                                                                                        {23, "Defog Current Measurement Fault - Measured Lower than Setpoint"},
                                                                                        {24, "GI Current Measurement Fault - Measured Higher than Setpoint"},
                                                                                        {25, "GI Current Measurement Fault - Measured Lower than Setpoint"},
                                                                                        {26, "Mirror Down Current Measurement Fault - Measured Higher than Setpoint"},
                                                                                        {27, "Mirror Down Current Measurement Fault - Measured Lower than Setpoint"},
                                                                                        {28, "Mirror Left Current Measurement Fault - Measured Higher than Setpoint"},
                                                                                        {29, "Mirror Left Current Measurement Fault - Measured Lower than Setpoint"},
                                                                                        {30, "Mirror Right Current Measurement Fault - Measured Higher than Setpoint"},
                                                                                        {31, "Mirror Right Current Measurement Fault - Measured Lower than Setpoint"},
                                                                                        {32, "Mirror Up Measurement Fault - Measured Higher than Setpoint"},
                                                                                        {33, "Mirror Up Current Measurement Fault - Measured Lower than Setpoint"},
                                                                                        {34, "Turn Signal Current Measurement Fault - Measured Higher than Setpoint"},
                                                                                        {35, "Turn Signal Current Measurement Fault - Measured Lower than Setpoint"},
                                                                                        {36, "EC Current Measurement Fault - Measured Higher than Setpoint"},
                                                                                        {37, "EC Current Measurement Fault - Measured Lower than Setpoint"},
                                                                                        {38, "Cargo Lamp Current Measurement Fault - Measured Higher than Setpoint"},
                                                                                        {39, "Cargo Lamp Current Measurement Fault - Measured Lower than Setpoint"},
                                                                                        {40, "Power Fold Down Fault - Up Position Sensed"},
                                                                                        {41, "Power Fold Down Fault - Unknown Position"},
                                                                                        {42, "Power Fold Current Measurement Fault - Measured Higher than Setpoint"},
                                                                                        {43, "Power Fold Current Measurement Fault - Measured Lower than Setpoint"},
                                                                                        {44, "Power Fold Up Fault - Down Position Sensed"},
                                                                                        {45, "Power Fold Up Fault - Unknown Position"},
                                                                                        {46, "OATS Current Measurement Fault - Current Measured Higher than Setpoint"},
                                                                                        {47, "OATS Current Measurement Fault - Measured Lower Than Setpoint"},
                                                                                        {48, "CA Current Measurement Fault - Current Measured Higher than Setpoint"},
                                                                                        {49, "CA Current Measurement Fault - Measured Lower Than Setpoint"},
                                                                                        {50, "GPS Current Measurement Fault - Current Measured Higher than Setpoint"},
                                                                                        {51, "GPS Current Measurement Fault - Measured Lower Than Setpoint"},
                                                                                        {52, "Camera Current Measurement Fault - Current Measured Higher than Setpoint"},
                                                                                        {53, "Camera Current Measurement Fault - Measured Lower Than Setpoint"},
                                                                                        {54, "CA Wire Inspection Fault - CA Wire Not Detected on CA Part"},
                                                                                        {55, "CA Wire Inspection Fault - CA Wire Detected on CA Non-Part"},
                                                                                        {56, "Logo Lamp Inspection Fault - Camera Does not See Logo Lamp on Logo Lamp Part"},
                                                                                        {57, "Logo Lamp Inspection Fault - Camera Sees Logo Lamp on non Logo Lamp Part"},
                                                                                        {58, "EC Inspection Fault - Camera Does Not See EC on EC Part"},
                                                                                        {59, "EC Inspection Fault - Camera Sees EC on non EC Part"},
                                                                                        {60, "Aspheric Inspection Fault - Camera Does Not See Aspheric Glass on Aspheric Part"},
                                                                                        {61, "Aspheric Inspection Fault - Camera Sees Aspheric on non Aspheric Part"},
                                                                                        {62, "BZI Inspection Fault - Camera Does Not See BZI Etch on BZI Part"},
                                                                                        {63, "BZI Inspection Fault - Camera Sees BZI Etch on non BZI Part"},
                                                                                        {64, "BZI Lamp Inspection Fault - Camera Does not See BZI Lamp on BZI Part"},
                                                                                        {65, "BZI Lamp Inspection Fault - Camera Sees BZI Lamp on Non BZI Part"},
                                                                                        {66, "Camera Inspection Fault - Camera Does not see Video from Camera"},
                                                                                        {67, "Camera Inspection Fault - Camera Sees Video From non Camera Part"},
                                                                                        {68, "Cargo Lamp Inspection Fault - Camera Does Not See Cargo Lamp on Cargo Lamp Part"},
                                                                                        {69, "Cargo Lamp Inspection Fault - Camera Sees Cargo Lamp on Non Cargo Lamp Part"},
                                                                                        {70, "CoPlaner Inspection Fault - Camera Does Not See CoPlaner on CoPlaner Part"},
                                                                                        {71, "CoPlaner Inspection Fault - Camera Sees CoPlaner on Non CoPlaner Part"},
                                                                                        {72, "Defog Symbol Inspection Fault - Camera Does Not See Defog Symbol on Defog Symbol Part"},
                                                                                        {73, "Defog Symbol Inspection Fault - Camera Sees Defog Symbol on Non Defog Symbol Part"},
                                                                                        {74, "Find Hole Inspection Fault - Camera Failed to Find Hole"},
                                                                                        {75, "GI Inspection Fault - Camera Does not See GI Lamp on GI Part"},
                                                                                        {76, "GI Inspection Fault - Camera Sees GI Lamp on non GI Part"},
                                                                                        {77, "Glass Shape Inspection Fault - Camera Sees Flat Glass on Convex Part"},
                                                                                        {78, "Glass Shape Inspection - Camera Sees Flat Glass on Convex Part"},
                                                                                        {79, "Glass Inspection Fault - Camera Cannot Determine Glass Shape"},
                                                                                        {80, "Glass Text Inspection Fault - Camera Sees Non-English Text Option on English Text Part"},
                                                                                        {81, "Glass Text Inspection Fault - Camera Sees Non-Arabic Text Option on Arabic Text Part"},
                                                                                        {82, "Glass Text Inspection Fault - Camera Sees Non-Korean Text Option on Korean Text Part"},
                                                                                        {83, "Glass Text Inspection Fault - Camera Sees Non-None Text Option on None Text Part"},
                                                                                        {84, "Glass Text Inspection Fault - Camera Cannot Determine Text Type"},
                                                                                        {85, "Power Fold Symbol Inspection Fault - Camera Does not See Power Fold Symbol on Power Fold Symbol Part"},
                                                                                        {86, "Power Fold Symbol Inspection Fault - Camera Sees Power Fold Symbol on Non Power Fold Symbol Part"},
                                                                                        {87, "Turn Signal Inspection Fault - Camera Does not See Turn Signal Etch on Turn Signal Part"},
                                                                                        {88, "Turn Signal Inspection Fault - Camera Sees Turn Signal Etch on Non Turn Signal Part"},
                                                                                        {89, "Turn Singal Lamp Inspection Fault - Camera Does not See Turn Signal Lamp on Turn Signal Part"},
                                                                                        {90, "Turn Signal Lamp Inspection - Camera Sees Turn Signal Lamp on Non Turn Signal Part"},
                                                                                        {91, "Chrome Feature Inspection Fault - Chrome Feature Not Detected on Part with Chrome Feature"},
                                                                                        {92, "Chrome Feature Inspection Fault - Chrome Feature Detected on Part without Chrome Feature"},
                                                                                        {93, "Gasket Inspection Fault - Gasket Not Detected on Part with Gasket"},
                                                                                        {94, "Gasket Inspection Fault - Gasket Detected on Part without Gasket"},
                                                                                        {95, "Mirror Down Travel Fault - Measured Lower than Setpoint"},
                                                                                        {96, "Mirror Down Travel Fault - Measured Higher than Setpoint"},
                                                                                        {97, "Mirror Down Travel Rate Fault - Measured Lower than Setpoint"},
                                                                                        {98, "Mirror Down Travel Rate Fault - Measured Higher than Setpoint"},
                                                                                        {99, "Mirror Up Travel Fault - Measured Lower than Setpoint"},
                                                                                        {100, "Mirror Up Travel Fault - Measured Higher than Setpoint"},
                                                                                        {101, "Mirror Up Travel Rate Fault - Measured Lower than Setpoint"},
                                                                                        {102, "Mirror Up Travel Rate Fault - Measured Higher than Setpoint"},
                                                                                        {103, "Mirror InBoard (Left) Travel Fault - Measured Lower than Setpoint"},
                                                                                        {104, "Mirror InBoard (Left) Travel Fault - Measured Higher than Setpoint"},
                                                                                        {105, "Mirror InBoard (Left) Travel Rate Fault - Measured Lower than Setpoint"},
                                                                                        {106, "Mirror InBoard (Left) Travel Rate Fault - Measured Higher than Setpoint"},
                                                                                        {107, "Mirror OutBoard (Right) Travel Fault - Measured Lower than Setpoint"},
                                                                                        {108, "Mirror OutBoard (Right) Travel Fault - Measured Higher than Setpoint"},
                                                                                        {109, "Mirror OutBoard (Right) Travel Rate Fault - Measured Lower than Setpoint"},
                                                                                        {110, "Mirror OutBoard (Right) Travel Rate Fault - Measured Higher than Setpoint"},
                                                                                        {111, "Mirror Down Memory Fault - Measured Higher than Setpoint"},
                                                                                        {112, "Mirror Down Memory Fault - Measured Lower than Setpoint"},
                                                                                        {113, "Mirror Up Memory Fault - Measured Higher than Setpoint"},
                                                                                        {114, "Mirror Up Memory Fault - Measured Lower than Setpoint"},
                                                                                        {115, "Mirror InBoard (Left) Memory Fault - Measured Higher than Setpoint"},
                                                                                        {116, "Mirror InBoard (Left) Memory Fault - Measured Lower than Setpoint"},
                                                                                        {117, "Mirror OutBoard (Right) Memory Fault - Measured Higher than Setpoint"},
                                                                                        {118, "Mirror OutBoard (Right) Memory Fault - Measured Lower than Setpoint"},
                                                                                        {119, "Gimp Seal Inspection Fault - Gimp Seal Not Detected on Part with Gimp Seal"},
                                                                                        {120, "Gimp Seal Inspection Fault - Gimp Seal Detected on Part without Gimp Seal"},
                                                                                        {121, "Ground Check Inspection Fault - Ground Check Voltage Detected on Part"},
                                                                                        {122, "Ground Check Inspection Fault - Ground Check Voltage Not Detected on Part"},
                                                                                        {123, "Spare"},
                                                                                        {124, "Spare"},
                                                                                        {125, "Spare"},
                                                                                        {126, "Spare"},
                                                                                        {127, "Spare"}}

    Private ReadOnly _defaultMachineAlarms As New Dictionary(Of Integer, String) From {{0, "No Alarms Active"},
                                                                                        {1, "Vacuum Pressure Build Fault - Pressure Not Sensed"},
                                                                                        {2, "GI Check Home Fault - Work Position Sense"},
                                                                                        {3, "GI Check Home Fault - Unknown Position"},
                                                                                        {4, "GI Check Work Fault - Home Position Sensed"},
                                                                                        {5, "Gi Check Work Fault - Unkown Position"},
                                                                                        {6, "Part Lock Home Fault - Work Position Sensed"},
                                                                                        {7, "Part Lock Home Fault - Unknown Position"},
                                                                                        {8, "Part Lock Work Fault - Home Position Sensed"},
                                                                                        {9, "Part Lock Work Fault - Unknown Position"},
                                                                                        {10, "Pull Cylinder Clamps Home Fault - Work Position Sensed"},
                                                                                        {11, "Pull Cylinder Clamps Home Fault - Unknown Position"},
                                                                                        {12, "Pull Cylinder Clamps Work Fault - Home Position Sensed"},
                                                                                        {13, "Pull Cylinder Clamps Work Fault - Unknown Position"},
                                                                                        {14, "Pull Clyinder Rotate Home Fault - Work Position Sensed"},
                                                                                        {15, "Pull Cylinder Rotate Home Fault - Unknown Position"},
                                                                                        {16, "Pull Cylinder Rotate Work Fault - Home Position Sensed"},
                                                                                        {17, "Pull Cylinder Rotate Work Fault - Unknown Position"},
                                                                                        {18, "Release Hale Blocks Fault - Release Not Sensed"},
                                                                                        {19, "Trap Door Check Home Fault - Work Position Sensed"},
                                                                                        {20, "Trap Door Check Home Fault - Unknown Position"},
                                                                                        {21, "Trap Door Check Work Fault - Home Position Sensed"},
                                                                                        {22, "Trap Door Check Work Fault - Unknown Position"},
                                                                                        {23, "Vacuum Cup Home Fault - Work Position Sensed"},
                                                                                        {24, "Vacuum Cup Home Fault - Unknown Position"},
                                                                                        {25, "Vacuum Cup Work Fault - Home Position Sensed"},
                                                                                        {26, "Vacuum Cup Work Fault - Unknown Position"},
                                                                                        {27, "LED Enabled - LED Not Seen"},
                                                                                        {28, "Backlight Enabled - Lightning Not Seen"},
                                                                                        {29, "Part Stamp Fault - Stamp Not Sensed"}}

    Private ReadOnly _defaultSequenceStrings As New Dictionary(Of Integer, String) From {{0, "Waiting for Control Power (12V)"},
{1, "Waiting for Control Power (24V)"},
{2, "Machine in Manual Mode"},
{3, "Waiting for User Logged In"},
{4, "Checking Tote Quantity Done"},
{5, "Waiting for Tote Label To Print And Scan for BAAN"},
{6, "Waiting for Part Recipe"},
{7, "Waiting for Part Type Nest Validation"},
{9, "Waiting for Color Results"},
{10, "Clear Recipie"},
{11, "Waiting for Part Type Nest Validation"},
{12, ""},
{13, ""},
{14, ""},
{15, ""},
{16, ""},
{17, ""},
{18, ""},
{19, ""},
{20, "Place Part in Nest"},
{21, "Validate Part in Place"},
{22, "Waiting for Part Type Nest Validation"},
{23, "Clear Light Curtain"},
{24, "Waiting for Cycle Start"},
{25, "Waiting for PC Ready for Cycle"},
{26, ""},
{27, ""},
{28, ""},
{29, ""},
{30, "Centering Mirror"},
{31, "Start PreTest (Glass and Lamp Inspection)"},
{32, "Waiting for PreTest to Complete (Glass and Lamp Inspection)"},
{33, "Start Options Test for Options Not Involving Glass Connections"},
{34, "Centering Mirror"},
{35, ""},
{36, ""},
{37, ""},
{38, ""},
{39, ""},
{40, "Mirror Up - Set Memory Offsets and Sample Initial Position"},
{41, "Move Mirror Up"},
{42, "Centering Mirror"},
{43, ""},
{44, ""},
{45, "Mirror Down - Set Memory Offsets and Sample Initial Position"},
{46, "Move Mirror Down"},
{47, "Centering Mirror"},
{48, ""},
{49, ""},
{50, "Mirror Inboard (Left) - Set Memory Offsets and Sample Initial Position"},
{51, "Move Mirror InBoard (Left)"},
{52, "Centering Mirror"},
{53, ""},
{54, ""},
{55, "Mirror Outboard (Right) - Set Memory Offsets and Sample Initial Position"},
{56, "Move Mirror OutBoard (Right)"},
{57, "Centering Mirror"},
{58, ""},
{59, ""},
{60, "Start Options Test Involving Glass Connections"},
{61, "Checking EC Darkening"},
{62, ""},
{63, ""},
{64, ""},
{65, "Start Pull Test"},
{66, ""},
{67, ""},
{68, ""},
{69, ""},
{70, "Waiting For Pull Test to Complete"},
{71, "Checking EC Lightening"},
{72, ""},
{73, ""},
{74, ""},
{75, "Waiting for Options Test to Complete"},
{76, ""},
{77, ""},
{78, "Wait for Part To Become Domino Current Part"},
{79, "Set Cycle Results"},
{80, "Create Cycle Log"},
{81, "Wait for Part Lable Confirming Scan"},
{82, ""},
{83, ""},
{84, ""},
{85, "Waiting for Part PStamp Complete"},
{86, "Release Part"},
{87, "Remove Part"},
{88, "Clear Light Curtain"},
{89, ""},
{90, ""},
{91, ""},
{92, ""},
{93, ""},
{94, ""},
{95, "Clear Light Curtain"},
{96, "Part Failed Create Cycle Log"},
{97, "Part Failed Press Opto-Touch To Restart Cycle"},
{98, ""},
{99, ""},
{100, "Final Step, Resetting Sequence"}}

    Public ReadOnly Property DefaultSequenceStrings As Dictionary(Of Integer, String) Implements IStringDefaults.DefaultSequenceStrings
        Get
            Return _defaultSequenceStrings
        End Get
    End Property

    Public ReadOnly Property DefaultMachineAlarms As Dictionary(Of Integer, String) Implements IStringDefaults.DefaultMachineAlarms
        Get
            Return _defaultMachineAlarms
        End Get
    End Property

    Public ReadOnly Property DefaultPartAlarms As Dictionary(Of Integer, String) Implements IStringDefaults.DefaultPartAlarms
        Get
            Return _defaultPartAlarms
        End Get
    End Property

End Class