Public Class BaseSharedSetPoints
    Public LeftHand As Boolean
    Public ElecReq As Boolean
    Public Memory_Req As Boolean
    Public Trap_Door_Req As Boolean
    Public Chrome_Req As Boolean
    Public Gasket_Req As Boolean
    Public GI_Filled_Req As Boolean
    Public TS_Filled_Req As Boolean
    Public PF_Req As Boolean
    Public SGI_Req As Boolean
    Public TSReq As Boolean
    Public SpotLight_Req As Boolean
    Public CameraReq As Boolean
    Public GI_Req As Boolean
    Public Up_Angle_Min As Single
    Public UpSpeed_Min As Single
    Public UpSpeed_Max As Single
    Public MirrorUp_Amps_Min As Single
    Public MirrorUp_Amps_Max As Single
    Public Down_Angle_Min As Single
    Public DnSpeed_Min As Single
    Public DnSpeed_Max As Single
    Public MirrorDn_Amps_Min As Single
    Public MirrorDn_Amps_Max As Single
    Public Inboard_Angle_Min As Single
    Public IbSpeed_Min As Single
    Public IbSpeed_Max As Single
    Public MirrorIb_Amps_Min As Single
    Public MirrorIb_Amps_Max As Single
    Public Outboard_Angle_Min As Single
    Public ObSpeed_Min As Single
    Public ObSpeed_Max As Single
    Public MirrorOb_Amps_Min As Single
    Public MirrorOb_Amps_Max As Single
    Public Up_Mem_Min As Single
    Public Up_Mem_Max As Single
    Public Up_Delta_Min As Single
    Public Dn_Mem_Min As Single
    Public Dn_Mem_Max As Single
    Public Dn_Delta_Min As Single
    Public IB_Mem_Min As Single
    Public IB_Mem_Max As Single
    Public IB_Delta_Min As Single
    Public OB_Mem_Min As Single
    Public OB_Mem_Max As Single
    Public OB_Delta_Min As Single
    Public GI_Amps_Min As Single
    Public GI_Amps_Max As Single
    Public SGI_Amps_Min As Single
    Public SGI_Amps_Max As Single
    Public TurnSignal_Amps_Min As Single
    Public TurnSignal_Amps_Max As Single
    Public Camera_Amps_Min As Single
    Public Camera_Amps_Max As Single
    Public SpotLight_Amps_Min As Single
    Public SpotLight_Amps_Max As Single
    Public PF_AmpsMax As Single
    Public PF_AmpsMin As Single
    Public PF_TimeMin As Single
    Public PF_TimeMax As Single
End Class
