Namespace TesterApi

    Public Class Udt_PartOptions

        'Removed Glass items and placed them in GlassOptions
        Public Electric As New Udt_Opt_Item()
        Public Memory As New Udt_Opt_Item()
        Public Defog As New Udt_Opt_Item()
        Public Turn_Signal As New Udt_Opt_Item()
        Public ChromeFeature As New Udt_Opt_Item()
        Public Gasket As New Udt_Opt_Item()
        Public Gimp_Seal As New Udt_Opt_Item()
        Public Bzi As New Udt_Opt_Item()
        Public GI As New Udt_Opt_Item()
        Public Logo_Lamp As New Udt_Opt_Item()
        Public Ec_Glass As New Udt_Opt_Item()
        Public TrapDoor As New Udt_Opt_Item()
        Public PullTest As New Udt_Opt_Item()
        Public PowerFold As New Udt_Opt_Item()
        Public GroundCheck As New Udt_Opt_Item()
        Public Zebra As New Udt_Opt_Item()
        Public Color As New Udt_Opt_Item()
        Public Camera_Vision As New Udt_Opt_Item()
        Public Police_Flasher As New Udt_Opt_Item()
        'Public AutoFold As New Udt_Opt_Item()
        'Public Actuator As New Udt_Opt_Item()
        'Public PowerExt As New Udt_Opt_Item()
        'Public Oats As New Udt_Opt_Item()
        'Public CargoLamp As New Udt_Opt_Item()
        'Public GPS As New Udt_Opt_Item()
        'Public CA As New Udt_Opt_Item()
        'Public BlackLabel As Udt_Opt_Item()
        'Public Gloss_base As Udt_Opt_Item()
        'Public JoyStick As New Udt_Opt_Item()
    End Class

    'Public Class Model_PartOptions
    '    'Removed Glass items and placed them in GlassOptions
    '    Public Electric As New Model_Opt_Item()
    '    Public Memory As New Model_Opt_Item()
    '    Public Defog As New Model_Opt_Item()
    '    Public Turn_Signal As New Model_Opt_Item()
    '    Public ChromeFeature As New Model_Opt_Item()
    '    Public Gasket As New Model_Opt_Item()
    '    Public Gimp_Seal As New Model_Opt_Item()
    '    Public Bzi As New Model_Opt_Item()
    '    Public BZM As New Model_Opt_Item()
    '    Public GI As New Model_Opt_Item()
    '    Public Logo_Lamp As New Model_Opt_Item()
    '    Public Ec_Glass As New Model_Opt_Item()
    '    Public TrapDoor As New Model_Opt_Item()
    '    Public PullTest As New Model_Opt_Item()
    '    Public PowerFold As New Model_Opt_Item()
    '    Public GroundCheck As New Model_Opt_Item()
    '    Public PowerExt As New Model_Opt_Item()
    '    Public Zebra As New Model_Opt_Item()
    '    Public Color As New Model_Opt_Item()
    '    Public Camera_Vision As New Model_Opt_Item()
    '    Public Actuator As New Model_Opt_Item()
    '    Public JoyStick As New Model_Opt_Item()
    '    Public Oats As New Model_Opt_Item()
    '    Public CargoLamp As New Model_Opt_Item()
    '    Public GPS As New Model_Opt_Item()
    '    Public CellularAntenna As New Model_Opt_Item()
    'End Class
End Namespace