'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Magna.DualTester.Domino.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property arw04dn() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("arw04dn", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property arw04lt() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("arw04lt", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property arw04rt() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("arw04rt", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property arw04up() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("arw04up", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property arw06dn() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("arw06dn", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property arw06lt() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("arw06lt", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property arw06rt() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("arw06rt", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property arw06up() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("arw06up", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property ARWDWN() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ARWDWN", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property ARWLeft() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ARWLeft", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property ARWRight() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ARWRight", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property ARWUP() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ARWUP", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property bullet_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bullet_green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property bullet_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bullet_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property bullet_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bullet_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Bzi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bzi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property CR() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("CR", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property defog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property dvt() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("dvt", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property GroundCheck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GroundCheck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property HtrSymb() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("HtrSymb", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property LED() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("LED", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property lightoff() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("lightoff", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property lighton() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("lighton", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property RubberStamp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("RubberStamp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property SECUR02A() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("SECUR02A", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property SECUR02B() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("SECUR02B", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property SINEWAVE() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("SINEWAVE", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property SOL() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("SOL", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Turn_Signal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Turn_Signal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
